"""add subscription fields

Revision ID: dc3f759ebba7
Revises: ef3d4c7d0912
Create Date: 2026-05-13 10:04:42.994038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc3f759ebba7'
down_revision: Union[str, Sequence[str], None] = 'ef3d4c7d0912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_table('trades')
    op.add_column('users', sa.Column('subscription_product_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('purchase_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_platform', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('auto_renewing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_renewing')
    op.drop_column('users', 'subscription_expiry')
    op.drop_column('users', 'subscription_platform')
    op.drop_column('users', 'purchase_token')
    op.drop_column('users', 'subscription_product_id')
    op.create_table('trades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trade_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trades_pkey'))
    )
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    # ### end Alembic commands ###
